@baseUrlV1 = http://localhost:3333/api/v1

GET {{baseUrlV1}}/users
###
GET {{baseUrlV1}}/users/1

###
POST {{baseUrlV1}}/users
Content-Type: application/json

{
    "identifier": "161250533419",
    "full_name": "Nguyễn Thế Lân",
    "sex": true,
    "date": "1997-29-05",
    "address": "04 Hải hồ, Q hải châu",
    "email": "test@gmail.com"
}


#============= Course api
###
GET {{baseUrlV1}}/courses

###
POST {{baseUrlV1}}/courses
Content-Type: application/json

{
    "name": "Học tiếng anh cùng với TEDDY",
    "descriptions": "Dành cho các bạn nhỏ dưới 12 tuổi",
    "credits": 100000,
    "instructor_id": 4
}

###
PUT {{baseUrlV1}}/courses/2
Content-Type: application/json

{
    "name": "Học tiếng anh cùng với TEDDY",
    "descriptions": "Dành cho các bạn nhỏ dưới 12 tuổi",
    "credits": 1000.501,
    "instructor_id": 4
}

###
GET {{baseUrlV1}}/courses/1

###
DELETE  {{baseUrlV1}}/courses/1

#============= class api
###
GET {{baseUrlV1}}/classes

###
POST {{baseUrlV1}}/classes
Content-Type: application/json

{
    "class_name": "Fullstack developer",
    "class_code": "24F1"
}

###
POST {{baseUrlV1}}/classes/1
Content-Type: application/json

{
    "class_name": "Fullstack developer",
    "class_code": "24F1"
}


###
DELETE  {{baseUrlV1}}/classes/1

